### ISSUE TITLE
Update EXT DESC for CWE-1248 - Issue with phrase "Security Guarantees

### ISSUE THREAD

**Issue by BobH-MITRE** [CWE-CAPEC/hw-cwe-sig#2]
The SIG Community is having an issue with the phrase "security guarantees" in the extended description.  Some have issues with the semantics of products are incapable of making claims, and others have an issue with the language as there may be specific legal consequences of the term.

The sentence under scrutiny is:
**If such faults occur in security-sensitive hardware modules, security guarantees offered by the device will be compromised.**

There are two proposals at the moment.  
        

1. Hareesh proposes, "If such faults occur in security-sensitive hardware modules, security guarantees offered by the device **vendors/ manufacturers** will be compromised."  
2. Jim Wesselkamper proposed: "If such faults occur in security-sensitive hardware modules, the **security objectives of the hardware module** may be compromised.”

(internal tracker #725)

**Comment by BobH-MITRE** [comment]
Jason Oberg writes: 

Bob and All,

Agree that we should drop "guarantees" from this description.

I personally vote for Jim's proposed language. I think "security objectives" instead of "security guarantees" more accurately depicts the intent. This also works well when thinking of the common definition of security objective being one or more of confidentiality, integrity, or availability. 

Regards,
Jason

**Comment by BobH-MITRE** [comment]
Joe J writes:

I also agree with Jim's proposed language using "security objectives" instead of "security guarantees" to more accurately describe the intent.

**Comment by BobH-MITRE** [comment]
**The proposed update to CWE-1248 Extended Description:**

A semiconductor device can fail for various reasons. While some are manufacturing and packaging defects, the rest are due to prolonged use or usage under extreme conditions. Some mechanisms that lead to semiconductor defects include encapsulation failure, die-attach failure, wire-bond failure, bulk-silicon defects, oxide-layer faults, aluminum-metal faults (including electromigration, corrosion of aluminum, etc.), and thermal/electrical stress. These defects manifest as faults on chip-internal signals or registers, have the effect of inputs, outputs, or intermediate signals being always 0 or always 1, and do not switch as expected. _If such faults occur in security-sensitive hardware modules, the **security objectives of the hardware module** may be compromised._

**Comment by BobHeinemann** [comment]
The proposed update has been accepted by the community and is currently staged in the cwe dev environment and will be part of the next release.

**Comment by BobH-MITRE** [comment]
The community has accepted the proposed update. The change is now staged in the CWE dev environment and will be part of the next release.
